### createUser
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "foo@bar.com",
    "password": "a12dmi34n
}

### whoAmI - get currently signed in user
GET http://localhost:3000/auth/whoami


### signin
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "foo2077@bar.com",
    "password": "111111"
}

### signout
POST http://localhost:3000/auth/signout

### findUser
GET http://localhost:3000/auth/1

### findAllUsers by email
GET http://localhost:3000/auth?email=foo2@bar.com

### removeUser by id
DELETE http://localhost:3000/auth/4

### updateUser by id
PATCH http://localhost:3000/auth/1
content-type: application/json

{
    "email": "foo2124@bar.com"
}


